server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/physical_exercise?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher  # 解决 Swagger 3.0 与 Spring Boot 2.6+ 不兼容的问题 
  # 文件上传配置
  servlet:
    multipart:
      # 单个文件大小限制
      max-file-size: 10MB
      # 总上传数据大小限制
      max-request-size: 100MB
      # 文件写入磁盘的阈值
      file-size-threshold: 2KB

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath*:/mapper/**/*.xml

# JWT配置
jwt:
  # 这是一个 Base64 编码的 64 字节密钥
  secret: "bXlfc3VwZXJfc2VjcmV0X2tleV90aGF0X2lzX2xvbmdfZW5vdWdoX2Zvcl9oczUxMl9hbGdvcml0aG1fYW5kX2l0X2lzX2Jhc2U2NF9lbmNvZGVk"
  expiration: 86400000  # 24小时

# 添加日志配置
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.boot.web.embedded.tomcat: DEBUG
    org.apache.tomcat: DEBUG
    org.apache.catalina: DEBUG

# MinIO配置
minio:
  endpoint: http://localhost:9005
  accessKey: admin
  secretKey: 12345678
  bucket: avatars
  public: true  # 允许公共访问
